### ISSUE TITLE
Twitter fails with "could not find the guest token"

### ISSUE THREAD

**Issue by utrack** [j6k4m8/goosepaper#31]
Hi, thanks for the great tool :) 

I've tried running Docker image w/ the example config and got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/goosepaper", line 33, in <module>
    sys.exit(load_entry_point('goosepaper', 'console_scripts', 'goosepaper')())
  File "/goosepaper/goosepaper/__main__.py", line 56, in main
    paper.to_pdf(args.output)
  File "/goosepaper/goosepaper/goosepaper.py", line 102, in to_pdf
    html = self.to_html()
  File "/goosepaper/goosepaper/goosepaper.py", line 44, in to_html
    stories = self.get_stories()
  File "/goosepaper/goosepaper/goosepaper.py", line 31, in get_stories
    new_stories = prov.get_stories()
  File "/goosepaper/goosepaper/twitter.py", line 98, in get_stories
    TwitterStoryProvider(
  File "/goosepaper/goosepaper/twitter.py", line 48, in get_stories
    twint.run.Search(c)
  File "/usr/local/lib/python3.8/site-packages/twint/run.py", line 410, in Search
    run(config, callback)
  File "/usr/local/lib/python3.8/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/local/lib/python3.8/site-packages/twint/run.py", line 36, in __init__
    self.token.refresh()
  File "/usr/local/lib/python3.8/site-packages/twint/token.py", line 68, in refresh
    raise RefreshTokenException('Could not find the Guest token in HTML')
twint.token.RefreshTokenException: Could not find the Guest token in HTML
```

Commenting twitter out solved it, so it seems that Twitter module is broken right now.

**Comment by j6k4m8** [comment]
Oh dear, indeed it is! The relevant issue in the twint repo is https://github.com/twintproject/twint/issues/1061. 

I've rebuilt and pushed the docker container which ([possibly?](https://github.com/twintproject/twint/commit/4b30fa33991ccdf89c77471382daad3d3bc8c988)) has a fix: https://hub.docker.com/repository/docker/j6k4m8/goosepaper

Let me know if this fixes it for you? :)

**Comment by j6k4m8** [comment]
This has fixed this bug for me, please feel free to reopen if this doesn't work for you :) Unfortunately the twitter system is pretty flaky due to a ton of changes to the twitter endpoints that twint uses.
