### ISSUE TITLE
Issue with uplouding

### ISSUE THREAD

**Issue by Frederik-Edel** [j6k4m8/goosepaper#70]
Hello, i get an error when i try using this command to upload, I've been trying to figure it out but I'm still to noob. I think its a problem with my rmapi installation?!

docker run -it --rm -v C:\Users\frede\Git-Reps\Remarkable:/goosepaper/mount -v C:\Users\frede\.rmapy:/root/.rmapy j6k4m8/goosepaper goosepaper -c mount/example-config.json -o mount/Goosepaper.pdf --upload

> WARNING:weasyprint:Ignored `font-display: swap` at 6:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 14:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 22:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 30:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 37:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 44:3, descriptor not supported.
WARNING:weasyprint:Ignored `font-display: swap` at 51:3, descriptor not supported.
WARNING:weasyprint:Anchor defined twice: 'content'
WARNING:weasyprint:Anchor defined twice: 'acceptanceDate'
WARNING:weasyprint:Anchor defined twice: 'content'
WARNING:weasyprint:Anchor defined twice: 'acceptanceDate'
WARNING:weasyprint:Anchor defined twice: 'content'
WARNING:weasyprint:Anchor defined twice: 'acceptanceDate'
WARNING:weasyprint:Anchor defined twice: 'content'
WARNING:weasyprint:Anchor defined twice: 'acceptanceDate'
Traceback (most recent call last):
  File "/usr/local/bin/goosepaper", line 33, in <module>
    sys.exit(load_entry_point('goosepaper', 'console_scripts', 'goosepaper')())
  File "/goosepaper/goosepaper/__main__.py", line 52, in main
    upload(filepath=filename, multiparser=multiparser)
  File "/goosepaper/goosepaper/upload.py", line 112, in upload
    client = auth_client()
  File "/goosepaper/goosepaper/auth.py", line 8, in auth_client
    client = Client()
  File "/usr/local/lib/python3.8/site-packages/rmapy/api.py", line 39, in __init__
    config = config_dict or load()
  File "/usr/local/lib/python3.8/site-packages/rmapy/config.py", line 14, in load
    with open(config_file_path, 'r') as config_file:
IsADirectoryError: [Errno 21] Is a directory: '/root/.rmapy'

**Comment by j6k4m8** [comment]
Hi @Frederik-Edel, thank you for reporting this! Is your `C:\Users\frede.rmapy` path a file or a directory? (On my machine, I have a file called `.rmapy` in my home directory.) Perhaps this should be `C:\Users\frede\.rmapy`?

**Comment by Frederik-Edel** [comment]
Hello, on "C:\Users\fred2e is my home dir (win) and .rmapy is a folder, it was created during the installation of rmapi, do you know what thats supposed to be?

**Comment by j6k4m8** [comment]
I think this should be a file (not a directory) that contains your credentials; check out the beginning of [this tutorial](https://github.com/juruen/rmapi/blob/master/docs/tutorial-print-macosx.md) for some more context!

**Comment by kurt-rhee** [comment]
Hello, I am also having issues with uploading which are due to rmapi.  

I followed the tutorial in the link above, but got an Exec format error, I think this may be because I am running on Ubuntu.  I also noticed that there is an rmapy fork linked in the documentation, but I was not sure how to set up the rmapy fork.  I am not sure what mount means. 

Apologies for my low skill in programming.

**Comment by kurt-rhee** [comment]
I have tried going to goosepaper/goosepaper/auth.py

When running auth.py I get to the "Input a code from ..." prompt.  When I go to https://my.remarkable.com/connect/remarkable and log in, I just get a blank screen with no code displayed.  I have tried on both firefox and chrome.

Thank you again

**Comment by j6k4m8** [comment]
Unfortunately there does seem to be a problem with `rmapy`, and I am currently super busy and haven't had an opportunity to do a deep dive.

I am hoping to totally rewrite all of the authentication logic in this and in [remailable](https://github.com/remailable/remailable) soon because it's a huge bummer not to have these tools working! 

Are you able to access the page using this link?

https://my.remarkable.com/device/desktop/connect

**Comment by j6k4m8** [comment]
(PS: Thanks for your patience, and sorry it's taken a while! It's good to know people want to use this tool, it's been a labor of love and I really appreciate the reports!)

**Comment by j6k4m8** [comment]
I updated this repository to use my new [`remarkapy`](https://github.com/j6k4m8/remarkapy) library instead of rmapy and it should be working now :)
