### ISSUE TITLE
No package metadata was found

### ISSUE THREAD

**Issue by giovi321** [j6k4m8/goosepaper#78]
I have installed goosepaper but I receive the following error when I try to run it:

```
root@server:~$ goosepaper --config /root/goosepaper/config.json
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/goosepaper", line 33, in <module>
    sys.exit(load_entry_point('goosepaper', 'console_scripts', 'goosepaper')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/goosepaper", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for goosepaper
```

**Comment by j6k4m8** [comment]
How did you install goosepaper? Can you paste the commands you used? (And was it in a virtualenv etc)?

**Comment by giovi321** [comment]
I think there were some issues with my python installation, I started with a fresh virtual machine and it worked!

**Comment by j6k4m8** [comment]
Super, glad to hear it's working now!
